# Generated by Django 4.2.30 on 2026-04-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_unit_sap', models.CharField(max_length=50)),
                ('tech_id', models.CharField(max_length=50)),
                ('gas_station', models.CharField(default='GW01', max_length=50)),
                ('pit_location_id', models.CharField(max_length=50)),
                ('location_id', models.CharField(blank=True, max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('jam_isi', models.CharField(max_length=20)),
                ('hm_km_unit', models.FloatField()),
                ('last_hm', models.FloatField()),
                ('consumed_qty', models.FloatField()),
                ('flow_meter_value', models.FloatField()),
                ('fluid_type', models.CharField(default='FUEL-DIESEL', max_length=50)),
                ('measuring_position', models.CharField(default='FUEL', max_length=50)),
                ('header_text', models.CharField(default='FUEL_TRX', max_length=100)),
                ('entry_type', models.CharField(default='NORMAL', max_length=20)),
                ('ai_hm_read', models.FloatField(blank=True, null=True)),
                ('ai_flow_read', models.FloatField(blank=True, null=True)),
                ('final_hm_value', models.FloatField(blank=True, null=True)),
                ('final_flow_value', models.FloatField(blank=True, null=True)),
                ('screening_status', models.CharField(default='Pending', max_length=20)),
                ('is_transferred', models.IntegerField(default=1)),
                ('hm_foto', models.TextField(blank=True, null=True)),
                ('flow_meter_foto', models.TextField(blank=True, null=True)),
                ('hm_foto_full', models.TextField(blank=True, null=True)),
                ('flow_meter_foto_full', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
