# Generated by Django 4.2.30 on 2026-04-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransaction',
            name='foto_unit',
            field=models.ImageField(blank=True, null=True, upload_to='fuel/unit/'),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='flow_meter_foto',
            field=models.ImageField(blank=True, null=True, upload_to='fuel/flow/'),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='flow_meter_foto_full',
            field=models.ImageField(blank=True, null=True, upload_to='fuel/full/'),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='hm_foto',
            field=models.ImageField(blank=True, null=True, upload_to='fuel/hm/'),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='hm_foto_full',
            field=models.ImageField(blank=True, null=True, upload_to='fuel/full/'),
        ),
    ]
