# Generated by Django 5.2.13 on 2026-04-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fueltransaction_foto_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransaction',
            name='flow_status',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='hm_status',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
