# Generated by Django 5.2.13 on 2026-04-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fueltransaction_flow_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransaction',
            name='date_screening',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='date_transferred',
            field=models.DateField(blank=True, null=True),
        ),
    ]
