# Generated by Django 5.2.13 on 2026-05-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fueltransaction_date_screening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransaction',
            name='filling_activity',
            field=models.CharField(blank=True, default='OFI', max_length=50, null=True),
        ),
    ]
