# Generated by Django 5.2.13 on 2026-05-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fueltransaction_filling_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueltransaction',
            name='filling_activity',
        ),
    ]
