# Generated by Django 5.2.13 on 2026-05-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_fueltransaction_filling_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransaction',
            name='filling_activity',
            field=models.CharField(blank=True, default='OFI', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='flowmeter_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
