# Generated by Django 5.2.13 on 2026-05-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fueltransaction_filling_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransaction',
            name='foto_surat_jalan',
            field=models.ImageField(blank=True, null=True, upload_to='fuel/full/'),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='id_transaction',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='id_transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='location_tujuan_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='qty_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='sync_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='vendor_delivery_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
