# Generated by Django 4.2.30 on 2026-06-21 03:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fueltransaction_foto_surat_jalan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_model', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterBudgetUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Start of the budget period')),
                ('end_date', models.DateField(default=django.utils.timezone.now, help_text='End of the budget period')),
                ('target_unit_qty', models.IntegerField(default=0, help_text='Target number of units')),
                ('total_budget', models.DecimalField(decimal_places=2, help_text='Total budget amount', max_digits=15)),
                ('desc', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='api.modelunit')),
            ],
            options={
                'verbose_name_plural': 'Master Budget Units',
                'unique_together': {('unit_model', 'start_date', 'end_date')},
            },
        ),
    ]
