# Generated by Django 4.2.30 on 2026-06-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_modelunit_masterbudgetunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterBudgetUnit',
        ),
        migrations.DeleteModel(
            name='ModelUnit',
        ),
    ]
