# Generated by Django 5.2.13 on 2026-06-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_modelunit_masterbudgetunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
